### ISSUE TITLE
Something's broken?

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [PBorocz/raindrop-io-py#12]
Getting this error while running `list_collections.py` from examples/
```
Traceback (most recent call last):
  File "/home/lima/list_collections.py", line 45, in <module>
    for collection in Collection.get_collections(api):
  File "/home/lima/.local/share/virtualenvs/raindrop/lib/python3.10/site-packages/raindropiopy/models.py", line 277, in get_collections
    return cls.get_root_collections(api) + cls.get_child_collections(api)
  File "/home/lima/.local/share/virtualenvs/raindrop/lib/python3.10/site-packages/raindropiopy/models.py", line 264, in get_child_collections
    return [cls(**item) for item in items]
  File "/home/lima/.local/share/virtualenvs/raindrop/lib/python3.10/site-packages/raindropiopy/models.py", line 264, in <listcomp>
    return [cls(**item) for item in items]
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Collection
parent
  value is not a valid integer (type=type_error.integer)
  ```

**Comment by PBorocz** [comment]
Interesting! I've never used nested collections before but confirmed that when I set one up, ran into this exact issue as well....on it.
Thanks for the feedback!

**Comment by PBorocz** [comment]
Thanks @limaceous-bushwhacker; I believe this is now addressed!
