### ISSUE TITLE
Error when getting large number of raindrops

### ISSUE THREAD

**Issue by andrewjslack** [PBorocz/raindrop-io-py#14]
Trying to get all unsorted bookmarks using the example in the docs:  

```python
print("\nUnsorted Raindrop Bookmarks:")
for item in Raindrop.search(api, collection=CollectionRef.Unsorted):
   print(item.title)
```

But running into an issue with the length of results. (Unsorted bookmarks is a large collection). Is there a better way to handle this or request a subset of results with each request?

Traceback:

> Traceback (most recent call last):
>   File "/Documents/fetchRaindrop.py", line 12, in <module>
>     for item in Raindrop.search(api, collection=CollectionRef.Unsorted):
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Documents/.venv/lib/python3.11/site-packages/raindropiopy/models.py", line 951, in search
>     while raindrops := Raindrop._search_paged(
>                        ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Documents/.venv/lib/python3.11/site-packages/raindropiopy/models.py", line 926, in _search_paged
>     return [cls(**item) for item in results["items"]]
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Documents/.venv/lib/python3.11/site-packages/raindropiopy/models.py", line 926, in <listcomp>
>     return [cls(**item) for item in results["items"]]
>             ^^^^^^^^^^^
>   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for Raindrop
> link
>   ensure this value has at most 2083 characters (type=value_error.any_str.max_length; limit_value=2083)

**Comment by PBorocz** [comment]
I'm not sure this has anything to do with the number of bookmarks. The error raised is from pydantic, specifically complaining about the max length of the `link` attribute (specifically the pydantic `HttpUrl` type). I'll so do poking around to see if this restriction should/can be relaxed.

**Comment by PBorocz** [comment]
Closing as this as it would require changing from pydantics' HttpUrl type to a simple char one. From cursory reading, pydantic's limit of 2083 seems somewhat short, here's a reasonably recent discussion: [Reddit: Maximum Length of an URL](https://www.reddit.com/r/webdev/comments/1nqufyc/maximum_length_of_an_url/).
